//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.NetConf2021.Maui.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.NetConf2021.Maui.Resources.Strings.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodownload using data.
        /// </summary>
        internal static string Autodownload_Using_Data {
            get {
                return ResourceManager.GetString("Autodownload_Using_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on to allow to download over cellular data if wifi is unavailable..
        /// </summary>
        internal static string Autodownload_Using_Data_Subtitle {
            get {
                return ResourceManager.GetString("Autodownload_Using_Data_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string Dark_Mode {
            get {
                return ResourceManager.GetString("Dark_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete played episodes.
        /// </summary>
        internal static string Delete_Played_Episodes {
            get {
                return ResourceManager.GetString("Delete_Played_Episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        internal static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download settings.
        /// </summary>
        internal static string Download_Settings {
            get {
                return ResourceManager.GetString("Download_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen Later.
        /// </summary>
        internal static string Listen_Later {
            get {
                return ResourceManager.GetString("Listen_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove episode.
        /// </summary>
        internal static string Listen_Later_Remove_Episode {
            get {
                return ResourceManager.GetString("Listen_Later_Remove_Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        internal static string Listen_Later_Short {
            get {
                return ResourceManager.GetString("Listen_Later_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen Together.
        /// </summary>
        internal static string Listen_Together {
            get {
                return ResourceManager.GetString("Listen_Together", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together.
        /// </summary>
        internal static string Listen_Together_Short {
            get {
                return ResourceManager.GetString("Listen_Together_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi only.
        /// </summary>
        internal static string Only_Wifi {
            get {
                return ResourceManager.GetString("Only_Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play or pause episode.
        /// </summary>
        internal static string Play_Or_Pause {
            get {
                return ResourceManager.GetString("Play_Or_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Categories.
        /// </summary>
        internal static string See_All_Categories {
            get {
                return ResourceManager.GetString("See_All_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to listen later.
        /// </summary>
        internal static string Semantic_Description_Tap_Listen_Later {
            get {
                return ResourceManager.GetString("Semantic_Description_Tap_Listen_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to play or pause an episode.
        /// </summary>
        internal static string Semantic_Description_Tap_Play_Episode {
            get {
                return ResourceManager.GetString("Semantic_Description_Tap_Play_Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to search text.
        /// </summary>
        internal static string Semantic_Description_Tap_Search {
            get {
                return ResourceManager.GetString("Semantic_Description_Tap_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to see all categories.
        /// </summary>
        internal static string Semantic_Description_Tap_See_All_Categories {
            get {
                return ResourceManager.GetString("Semantic_Description_Tap_See_All_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to select a category.
        /// </summary>
        internal static string Semantic_Description_Tap_Select {
            get {
                return ResourceManager.GetString("Semantic_Description_Tap_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to subscribe a podcast.
        /// </summary>
        internal static string Semantic_Description_Tap_Subscribe_Podcast {
            get {
                return ResourceManager.GetString("Semantic_Description_Tap_Subscribe_Podcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable dark mode.
        /// </summary>
        internal static string Semantic_Description_Toggle_Mode {
            get {
                return ResourceManager.GetString("Semantic_Description_Toggle_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable wifi settings.
        /// </summary>
        internal static string Semantic_Description_Toggle_Wifi {
            get {
                return ResourceManager.GetString("Semantic_Description_Toggle_Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcasts demo App developed in MAUI.
        /// </summary>
        internal static string Settings_Info {
            get {
                return ResourceManager.GetString("Settings_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specially for you.
        /// </summary>
        internal static string Specially_For_You {
            get {
                return ResourceManager.GetString("Specially_For_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed.
        /// </summary>
        internal static string Subscribed {
            get {
                return ResourceManager.GetString("Subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        internal static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What’s new.
        /// </summary>
        internal static string Whats_New {
            get {
                return ResourceManager.GetString("Whats_New", resourceCulture);
            }
        }
    }
}
