global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Maui;
global using Microsoft.Maui.Controls;
global using Microsoft.Maui.Essentials;
global using Microsoft.NetConf2021.Maui.Models;
global using Microsoft.NetConf2021.Maui.Pages;
global using Microsoft.NetConf2021.Maui.Services;
global using Microsoft.NetConf2021.Maui.ViewModels;
global using MvvmHelpers;
global using MvvmHelpers.Commands;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using System.Windows.Input;
global using System.Collections.ObjectModel;
global using Microsoft.NetConf2021.Maui.Helpers;

