name: Delete Deployment Environment
# foo
on:
  delete:
  pull_request:
    types: [closed]

concurrency: ${{ github.event.number || github.ref_name }}

jobs:
  config:
    name: Get Configuration
    uses: ./.github/workflows/environment-config.yml

  ade:
    name: Delete Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.ref_type == 'branch'

    needs: config

    environment:
      name: ${{ needs.config.outputs.type }}

    steps:
      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Install DevCenter CLI
        run: az extension add -y -s https://fidalgosetup.blob.core.windows.net/cli-extensions/devcenter-0.1.0-py3-none-any.whl

      - name: Delete Environment
        id: delete_env
        run: |
          az devcenter dev environment delete --dev-center ${{ needs.config.outputs.devcenter }} --project ${{ needs.config.outputs.project }} \
            --environment-name ${{ needs.config.outputs.name }} --user-id me --yes
