name: Podcast .NET MAUI Blazor CD

on:
  push:
    branches: [ main ]
    paths:
      - 'src/MobileBlazor/**'
      - '**/*build.props'      
      - '.github/workflows/podcast-dotnet-maui-blazor-cd.yml'
      - '.github/workflows/template-dotnet-maui-cd.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-mobile:
    uses: ./.github/workflows/template-dotnet-maui-cd.yml
    with:
      csproj: src/MobileBlazor/mauiapp/NetPodsMauiBlazor.csproj
      root_path: src/MobileBlazor/mauiapp/
      encrypted_keystore_path: deploy/Android/android-keystore-test.jks.gpg
      keystore_path: android-keystore-test.keystore
    secrets:
      android_keystore_gpg_pass: ${{secrets.ANDROID_KEYSTORE_GPG_PASSWORD}}
      android_signing_store_pass: ${{secrets.ANDROID_SIGNING_STORE_PASS}}
      android_signing_key_alias: ${{secrets.ANDROID_SIGNING_KEY_ALIAS}}
      android_signing_key_pass: ${{secrets.ANDROID_SIGNING_KEY_PASS}}
