name: Podcast .NET MAUI CI

on:
  workflow_dispatch: # allow workflow to be manually triggered

  push:
    branches: [main]
    paths:
      - 'src/Mobile/**'
      - 'src/Web/Components/**'
      - '**/*build.props'
      - '.github/workflows/podcast-dotnet-maui-ci.yml'
      - '.github/workflows/template-dotnet-maui-ci.yml'

  pull_request:
    branches:
      - '**'
    paths:
      - 'src/Mobile/**'
      - 'src/Web/Components/**'
      - '**/*build.props'
      - '.github/workflows/podcast-dotnet-maui-ci.yml'
      - '.github/workflows/template-dotnet-maui-ci.yml'

jobs:
  build-mobile:
    uses: ./.github/workflows/template-dotnet-maui-ci.yml
    with:
      csproj: src/Mobile/Microsoft.NetConf2021.Maui.csproj
